Repository AY2324S2-CS2103T-F10-4/tp, pull requests merged in 2024-04, with the labels that each got.

#73 Fix AddAssignment bugs
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/assignment/AssignmentDetails.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAssignmentParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug

#79 Delete assignment feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/main/java/seedu/address/model/assignment/exceptions/AssignmentNotFoundException.java
  src/main/java/seedu/address/model/assignment/exceptions/DuplicateAssignmentException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandParserTest.java
  src/test/java/seedu/address/model/assignment/AssignmentListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story, priority.High

#78 Copy command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CopyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CopyCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#80 Refresh Availabilities Feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RefreshCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/Availability.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/RefreshCommandTest.java
Labels: type.Story, priority.High

#85 Fixes for input field
  src/main/java/seedu/address/ui/AutoCompleteComboBoxPlus.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/AssignmentListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#81 Branch export csv
  .gitignore
  .vscode/settings.json
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExportSequenceDiagram-Logic.puml
  docs/images/ExportSequenceDiagram-Logic.png
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Story, priority.High

#97 Fix issue of wrong help message for dates with right format but are invalid eg. 01/99/2024
  .gitignore
  .vscode/settings.json
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Availability.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AvailabilityTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#101 Prevent duplicate phone and email
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug

#172 Fix UG, Add target user and value proposition
  docs/UserGuide.md
Labels: type.Bug

#174 Branch confirmation bug fix
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Bug, bug.MustFix

#176 Fix UG
  docs/UserGuide.md
Labels: type.Bug

#177 Fix data inconsistency
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RefreshCommand.java
  src/main/java/seedu/address/logic/commands/RemoveAvailCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/ConfirmationTest.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
Labels: type.Bug
